namespace Daiv3.ModelExecution.Models;

/// <summary>
/// User's inference request to be executed by a model.
/// </summary>
public class ExecutionRequest
{
    /// <summary>Unique request ID (generated by producer).</summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>Task type for model selection (e.g., "chat", "summarize", "code").</summary>
    public string TaskType { get; set; } = string.Empty;

    /// <summary>Request content (prompt, question, instruction, etc.).</summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>Contextual information (document references, memory, etc.).</summary>
    public Dictionary<string, string> Context { get; set; } = new();

    /// <summary>When request was created.</summary>
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
}
