using Daiv3.Persistence.Entities;
using Daiv3.Persistence.Repositories;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Xunit;

#pragma warning disable IDISP006 // Test classes don't need to implement IDisposable

namespace Daiv3.Persistence.Tests;

/// <summary>
/// Unit tests for GlossaryRepository.
/// Validates CRUD operations and specialized queries for glossary management.
/// Implements GLO-DATA-001: Glossary entries SHALL include term, definition, and related terms.
/// Uses in-memory SQLite database for isolation.
/// </summary>
public class GlossaryRepositoryTests : IAsyncLifetime
{
    private readonly IServiceProvider _serviceProvider;
    private readonly IDatabaseContext _databaseContext;
    private readonly IGlossaryRepository _repository;
    private readonly ILogger<GlossaryRepositoryTests> _logger;
    private readonly string _testDbPath;

    public GlossaryRepositoryTests()
    {
        // Use a temporary database file for each test
        _testDbPath = Path.Combine(Path.GetTempPath(), $"glossary-test-{Guid.NewGuid()}.db");

        var services = new ServiceCollection();
        services.AddLogging();

        services.Configure<PersistenceOptions>(options =>
        {
            options.DatabasePath = _testDbPath;
        });

        services.AddPersistence();

        _serviceProvider = services.BuildServiceProvider();
        _databaseContext = _serviceProvider.GetRequiredService<IDatabaseContext>();
        _repository = _serviceProvider.GetRequiredService<IGlossaryRepository>();
        _logger = _serviceProvider.GetRequiredService<ILogger<GlossaryRepositoryTests>>();
    }

    public async Task InitializeAsync()
    {
        await _databaseContext.InitializeAsync();
        _logger.LogInformation("Glossary test database initialized");
    }

    public async Task DisposeAsync()
    {
        await _databaseContext.DisposeAsync();

        try
        {
            if (File.Exists(_testDbPath))
            {
                File.Delete(_testDbPath);
            }
        }
        catch
        {
            // Ignore cleanup errors
        }
    }

    private static GlossaryEntry CreateTestEntry(
        string term, 
        string definition, 
        string? category = null,
        string? relatedTermsJson = null,
        string? notes = null)
    {
        var now = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        return new GlossaryEntry
        {
            GlossaryId = Guid.NewGuid().ToString(),
            Term = term,
            Definition = definition,
            Category = category,
            RelatedTermsJson = relatedTermsJson,
            Notes = notes,
            CreatedAt = now,
            UpdatedAt = now,
            CreatedBy = "test-system",
            UpdatedBy = "test-system"
        };
    }

    [Fact]
    public async Task AddAsync_ValidEntry_ReturnsGlossaryId()
    {
        // Arrange
        var entry = CreateTestEntry("Chunk", "A segment of text created by splitting documents into ~400 token segments.");

        // Act
        var id = await _repository.AddAsync(entry, CancellationToken.None);

        // Assert
        Assert.NotNull(id);
        Assert.Equal(entry.GlossaryId, id);
    }

    [Fact]
    public async Task GetByIdAsync_ExistingEntry_ReturnsEntry()
    {
        // Arrange
        var entry = CreateTestEntry("Embedding", "A vector representation of text generated by a neural network model.");
        var id = await _repository.AddAsync(entry, CancellationToken.None);

        // Act
        var retrieved = await _repository.GetByIdAsync(id, CancellationToken.None);

        // Assert
        Assert.NotNull(retrieved);
        Assert.Equal(entry.Term, retrieved.Term);
        Assert.Equal(entry.Definition, retrieved.Definition);
    }

    [Fact]
    public async Task GetByIdAsync_NonExistentId_ReturnsNull()
    {
        // Act
        var retrieved = await _repository.GetByIdAsync(Guid.NewGuid().ToString(), CancellationToken.None);

        // Assert
        Assert.Null(retrieved);
    }

    [Fact]
    public async Task UpdateAsync_ExistingEntry_UpdatesFields()
    {
        // Arrange
        var entry = CreateTestEntry("Tier", "Level of indexing strategy.");
        await _repository.AddAsync(entry, CancellationToken.None);
        
        entry.Definition = "Updated definition for tier-based indexing.";
        entry.UpdatedAt = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        entry.UpdatedBy = "test-user";

        // Act
        await _repository.UpdateAsync(entry, CancellationToken.None);

        // Assert
        var retrieved = await _repository.GetByIdAsync(entry.GlossaryId, CancellationToken.None);
        Assert.NotNull(retrieved);
        Assert.Equal("Updated definition for tier-based indexing.", retrieved.Definition);
    }

    [Fact]
    public async Task DeleteAsync_ExistingEntry_RemovesEntry()
    {
        // Arrange
        var entry = CreateTestEntry("Skill", "A reusable module that performs a specific task.");
        var id = await _repository.AddAsync(entry, CancellationToken.None);

        // Act
        await _repository.DeleteAsync(id, CancellationToken.None);

        // Assert
        var retrieved = await _repository.GetByIdAsync(id, CancellationToken.None);
        Assert.Null(retrieved);
    }

    [Fact]
    public async Task GetByTermAsync_CaseInsensitive_ReturnsEntry()
    {
        // Arrange
        var entry = CreateTestEntry("Vector Similarity", "Measurement of how similar two vectors are.");
        await _repository.AddAsync(entry, CancellationToken.None);

        // Act
        var retrieved = await _repository.GetByTermAsync("vector similarity", CancellationToken.None);

        // Assert
        Assert.NotNull(retrieved);
        Assert.Equal("Vector Similarity", retrieved.Term);
    }

    [Fact]
    public async Task GetByTermAsync_NonExistentTerm_ReturnsNull()
    {
        // Act
        var retrieved = await _repository.GetByTermAsync("NonExistentTerm", CancellationToken.None);

        // Assert
        Assert.Null(retrieved);
    }

    [Fact]
    public async Task GetByCategoryAsync_ValidCategory_ReturnsMultipleEntries()
    {
        // Arrange
        var architecture1 = CreateTestEntry("Layer", "Logical tier in the system architecture.", "Architecture");
        var architecture2 = CreateTestEntry("Interface", "Contract between system components.", "Architecture");
        var knowledge = CreateTestEntry("Document", "Source file containing knowledge.", "Knowledge");

        await _repository.AddAsync(architecture1, CancellationToken.None);
        await _repository.AddAsync(architecture2, CancellationToken.None);
        await _repository.AddAsync(knowledge, CancellationToken.None);

        // Act
        var entries = await _repository.GetByCategoryAsync("Architecture", CancellationToken.None);

        // Assert
        Assert.NotNull(entries);
        Assert.Equal(2, entries.Count);
        Assert.All(entries, e => Assert.Equal("Architecture", e.Category));
    }

    [Fact]
    public async Task GetByCategoryAsync_EmptyCategory_ReturnsEmptyList()
    {
        // Act
        var entries = await _repository.GetByCategoryAsync("NonExistentCategory", CancellationToken.None);

        // Assert
        Assert.NotNull(entries);
        Assert.Empty(entries);
    }

    [Fact]
    public async Task GetAllCategoriesAsync_MultipleCategories_ReturnsDistinct()
    {
        // Arrange
        await _repository.AddAsync(CreateTestEntry("T1", "D1", "Archive"), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("T2", "D2", "Architecture"), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("T3", "D3", "Knowledge"), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("T4", "D4", "Architecture"), CancellationToken.None);

        // Act
        var categories = await _repository.GetAllCategoriesAsync(CancellationToken.None);

        // Assert
        Assert.NotNull(categories);
        Assert.Equal(3, categories.Count);
        Assert.Contains("Architecture", categories);
        Assert.Contains("Knowledge", categories);
        Assert.Contains("Archive", categories);
    }

    [Fact]
    public async Task SearchByTermPrefixAsync_MatchingPrefix_ReturnsEntries()
    {
        // Arrange
        await _repository.AddAsync(CreateTestEntry("Vector", "Mathematical representation."), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("Vector Similarity", "Similarity measure."), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("Chunk", "Text segment."), CancellationToken.None);

        // Act
        var results = await _repository.SearchByTermPrefixAsync("Vector", 10, CancellationToken.None);

        // Assert
        Assert.NotNull(results);
        Assert.Equal(2, results.Count);
        Assert.All(results, r => Assert.StartsWith("Vector", r.Term));
    }

    [Fact]
    public async Task SearchByTermPrefixAsync_MaxResults_LimitsResults()
    {
        // Arrange
        await _repository.AddAsync(CreateTestEntry("A", "1"), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("Ab", "2"), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("Abc", "3"), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("Abcd", "4"), CancellationToken.None);

        // Act
        var results = await _repository.SearchByTermPrefixAsync("A", 2, CancellationToken.None);

        // Assert
        Assert.Equal(2, results.Count);
    }

    [Fact]
    public async Task SearchDefinitionAsync_MatchingText_ReturnsEntries()
    {
        // Arrange
        await _repository.AddAsync(CreateTestEntry("T1", "This is about vector operations."), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("T2", "Learns from vector data."), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("T3", "Completely different topic."), CancellationToken.None);

        // Act
        var results = await _repository.SearchDefinitionAsync("vector", 20, CancellationToken.None);

        // Assert
        Assert.NotNull(results);
        Assert.Equal(2, results.Count);
    }

    [Fact]
    public async Task SearchDefinitionAsync_CaseInsensitive_ReturnsMatches()
    {
        // Arrange
        await _repository.AddAsync(CreateTestEntry("T1", "This involves VECTOR operations."), CancellationToken.None);

        // Act
        var results = await _repository.SearchDefinitionAsync("vector", 20, CancellationToken.None);

        // Assert
        Assert.Single(results);
    }

    [Fact]
    public async Task GetCountAsync_MultipleEntries_ReturnsCorrectCount()
    {
        // Arrange
        await _repository.AddAsync(CreateTestEntry("T1", "D1"), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("T2", "D2"), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("T3", "D3"), CancellationToken.None);

        // Act
        var count = await _repository.GetCountAsync(CancellationToken.None);

        // Assert
        Assert.Equal(3, count);
    }

    [Fact]
    public async Task GetCountByCategoryAsync_ValidCategory_ReturnsCorrectCount()
    {
        // Arrange
        await _repository.AddAsync(CreateTestEntry("T1", "D1", "Cat1"), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("T2", "D2", "Cat1"), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("T3", "D3", "Cat2"), CancellationToken.None);

        // Act
        var count = await _repository.GetCountByCategoryAsync("Cat1", CancellationToken.None);

        // Assert
        Assert.Equal(2, count);
    }

    [Fact]
    public async Task GetModifiedDateRangeAsync_WithinRange_ReturnsEntries()
    {
        // Arrange
        var now = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        var rangeStart = now - 1000;
        var rangeEnd = now;

        var entry1 = CreateTestEntry("T1", "D1");
        entry1.UpdatedAt = now - 500; // Within range [now-1000, now]
        
        var entry2 = CreateTestEntry("T2", "D2");
        entry2.UpdatedAt = now + 500; // Outside range - after rangeEnd

        await _repository.AddAsync(entry1, CancellationToken.None);
        await _repository.AddAsync(entry2, CancellationToken.None);

        // Act
        var results = await _repository.GetModifiedDateRangeAsync(rangeStart, rangeEnd, CancellationToken.None);

        // Assert
        Assert.NotNull(results);
        Assert.Single(results); // Only entry1 is in range
        Assert.Equal("T1", results[0].Term);
    }

    [Fact]
    public async Task GetModifiedDateRangeAsync_OpenEndedRange_ReturnsAllAfterDate()
    {
        // Arrange
        var now = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        var before = now - 1000;

        var entry = CreateTestEntry("T1", "D1");
        entry.UpdatedAt = now - 500;
        await _repository.AddAsync(entry, CancellationToken.None);

        // Act
        var results = await _repository.GetModifiedDateRangeAsync(before, beforeDate: null, CancellationToken.None);

        // Assert
        Assert.NotNull(results);
        Assert.Single(results);
    }

    [Fact]
    public async Task GetAllAsync_MultipleEntries_ReturnsSortedByTerm()
    {
        // Arrange
        await _repository.AddAsync(CreateTestEntry("Zebra", "Z"), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("Apple", "A"), CancellationToken.None);
        await _repository.AddAsync(CreateTestEntry("Banana", "B"), CancellationToken.None);

        // Act
        var all = await _repository.GetAllAsync(CancellationToken.None);

        // Assert
        Assert.NotNull(all);
        Assert.Equal(3, all.Count);
        Assert.Equal("Apple", all[0].Term);
        Assert.Equal("Banana", all[1].Term);
        Assert.Equal("Zebra", all[2].Term);
    }

    [Fact]
    public async Task RoundTrip_WithRelatedTerms_PersistsAndRetrievesJson()
    {
        // Arrange
        var entry = CreateTestEntry("Document", "A file containing knowledge.", "Knowledge");
        entry.RelatedTermsJson = "[\"Text\", \"File\", \"Knowledge Base\"]";

        // Act
        await _repository.AddAsync(entry, CancellationToken.None);
        var retrieved = await _repository.GetByIdAsync(entry.GlossaryId, CancellationToken.None);

        // Assert
        Assert.NotNull(retrieved);
        Assert.Equal("[\"Text\", \"File\", \"Knowledge Base\"]", retrieved.RelatedTermsJson);
    }

    [Fact]
    public async Task RoundTrip_WithNotes_PersistsAndRetrievesNotes()
    {
        // Arrange
        var entry = CreateTestEntry("Agent", "An autonomous system that performs tasks.");
        entry.Notes = "Introduced in Phase 5 for advanced automation features.";

        // Act
        await _repository.AddAsync(entry, CancellationToken.None);
        var retrieved = await _repository.GetByIdAsync(entry.GlossaryId, CancellationToken.None);

        // Assert
        Assert.NotNull(retrieved);
        Assert.Equal("Introduced in Phase 5 for advanced automation features.", retrieved.Notes);
    }
}
